export enum AgentErrorCode {
  RATE_LIMITED = 'ERR_RATE_LIMITED',
  LLM_TIMEOUT = 'ERR_LLM_TIMEOUT',
  LLM_UNAVAILABLE = 'ERR_LLM_UNAVAILABLE',
  TOOL_TEMPORARILY_UNAVAILABLE = 'ERR_TOOL_TEMPORARILY_UNAVAILABLE',
  TOOL_FAILED = 'ERR_TOOL_FAILED',
  INSUFFICIENT_BALANCE = 'ERR_INSUFFICIENT_BALANCE',
  INVALID_BUNDLE = 'ERR_INVALID_BUNDLE',
  PROMPT_BLOCKED = 'ERR_PROMPT_BLOCKED',
  MAX_ITERATIONS = 'ERR_MAX_ITERATIONS',
}
